### PR TITLE
Ams/refac/get user id on be

### PR DESCRIPTION
**Pull request by espressoGoddess**
## What I did:
* This refactors all components to not need the `userID` (except for `Profile.tsx` because it is needed for the demo page)
* This updates the typing for AuthProps to not include `userID`
* This refactors the api routes to not need the `userID` and grabs them inside the route instead so that it is more trustworthy
* This updates the README to have local development install instructions for the DB
* This removes unused comments and console logs
* This uses the `DEMO_USER_ID` variable on all demo pages instead of hard coding it

## Testing Notes: 
* Did not change what is displayed, so testing should still pass

## Did this break anything?
- [X]  No
- [ ]  Yes
- [ ]  Potentially (explain)

## Type of change
- [X]  New feature (non-breaking change which adds functionality)
- [ ]  Bug fix (non-breaking change which fixes an issue)
- [X]  Refactor(DRY-ing up/ reorganizing code, etc.)
- [ ]  Super small fix (Corrected a typo, removed a comment, etc.)
- [ ]  Skip all the other stuff and briefly explain the fix.

## Checklist:
- [ ]  If this code needs to be tested, all tests are passing
- [X]  The code runs locally
- [X]  The code is DRY. If it's not, I tried my best
- [X]  I reviewed my code before pushing

## What's next?
* Refactor code to include a new route for adding a first time entry instead of calling the endpoint multiple times for each entry needing to be added
* Refactor the registration form to get the user's name and birthday, since the passage one is unreliable (it does not have verification for the date, which could cause the user's sign to be wrong)
* Refactor `utils/utils.ts` and break up the functions into their own file appropriately named
* Adjust the loading gif (I can only see the top half of it and have to scroll down to see "loading")

### CODE REVIEW

**Comment by sakisandrac** [comment]
I'm still getting that "Error loading insights message" whenever i add data, then go back to the day for insights, but I noticed I'm getting this error from ChatGPT code 429 " message: 'You exceeded your current quota, please check your plan and billing details.'" so it might just have to do with our calls running out. Everything else looks like its running the properly!

**Comment by sakisandrac** [comment]
> I'm still getting that "Error loading insights message" whenever i add data, then go back to the day for insights, but I noticed I'm getting this error from ChatGPT code 429 " message: 'You exceeded your current quota, please check your plan and billing details.'" so it might just have to do with our calls running out. Everything else looks like its running the properly!
> 
> Screenshot 2023-11-12 at 6 48 17 PM

Also since everything looks good besides that should i go ahead and merge?

**Comment by espressoGoddess** [comment]
When using the preview deployment, I am getting a 504 error, which means `the server, while acting as a gateway or proxy, did not receive a timely response from an upstream server it needed to access in order to complete the request`.
i *think* it's only the preview deployment that is affected. It runs just fine locally for me and I checked the balance on my open AI account and there are still funds in there. It runs just fine locally for me.

I think you can merge if you feel comfortable with it!

**Comment by sakisandrac** [comment]
@espressoGoddess okay great I will just merge it then, seems like its just a problem on my end! I'll double check the deployed again after merging to make sure it still works too. Thanks Amber!

**Pull request merged**
